### ISSUE TITLE
make individual bits of information linkable

### ISSUE THREAD

**Issue by designakt** [bwinton/StyleGuide#10]
When I want to reference the style guide, I usually have a particular part of a component in mind and would like to link to exactly that, and not to the top of the page.

e.g.I want to link to the 3rd recommendation on writing…
![screen shot 2017-02-17 at 18 02 56](https://cloud.githubusercontent.com/assets/8145891/23075060/57036338-f53b-11e6-8a62-2408c5ed4067.png)
… and not just to the top of that page.
![screen shot 2017-02-17 at 18 04 05](https://cloud.githubusercontent.com/assets/8145891/23075097/846bb686-f53b-11e6-900c-511af5595bc5.png)
https://bwinton.github.io/StyleGuide/#/writing

**Comment by aminalhazwani** [comment]
@designakt thanks for your feedback. @bwinton is currently working on a new approach that doesn't rely on `#` for page routing. It will then be able to directly point to anchor titles.
