### ISSUE TITLE
New proposition for content structure and creation

### ISSUE THREAD

**Issue by aminalhazwani** [bwinton/StyleGuide#12]
At the moment we place content files as `html` file under `/contents`. In order to make page creation more accessible I am currently rewriting the `css` in order to allow people to write plain `html` and no classes. See eg `/contents/color.html` on `css-refactor` branch. 

In some cases, like the page mentioned above, it is necessary to include more structured components that include `css` classes. This can make the whole writing experience a little bit cumbersome.

Instead of directly placing the `html` files under `/contents` we could create a folder for each page. For instance `/contents/color`. Under this folder we could place a `index.html` together with all necessary custom components like `color-palette.html`. Such elements could then be easily included in your `/contents/color/index.html` with a custom tag like `<include src="color-palette.html">`. This solution will allow content creators to have a more accessible file.

**Comment by bwinton** [comment]
So, as an alternative, what if we leave the pages where they are, but add directories for extra stuff that they reference?  So we would have `/contents/color.html`, but it would have `<include src="color/palette.html">` (or `<include src="shared/component.html">`)?  (Also, this will make loading pages slower, since instead of a single request to get the html for the content, we would now need a bunch, depending on how many things were included…  Might still be worth doing, but it's something we should think about.)

**Comment by aminalhazwani** [comment]
Yes, also your proposal could be a suitable solution! Regarding the page loading what if we compile the pages in the build process so that the call that loads the in-page content remains unique?

**Comment by bwinton** [comment]
Yeah, that makes sense.  And then they could be renamed to `color\index.html` if we wanted, too…  🙂

**Comment by bwinton** [comment]
(Clearing in case @ericawright wanted to take a stab at this…)

**Comment by aminalhazwani** [comment]
@bwinton @ericawright any update on this one? thank you 🙏

**Comment by bwinton** [comment]
I've been on work weeks for the last couple of weeks, and Erica has been working on more important stuff, so I'm afraid there's no update.  Fortunately, I'm back now, and I think I might have some time to start in on it.  🤞

**Comment by bwinton** [comment]
So, I've got something that I think will work in production, but doesn't work in local development…  😞
@ericawright, if you wanted to take a stab at getting it working in the webpack-dev-server mode, I'ld love to get another pair of eyes on it.
