### ISSUE TITLE
Page navigation

### ISSUE THREAD

**Issue by aminalhazwani** [bwinton/StyleGuide#13]
In the css-refactor branch the `index.html` features a page navigation inside `<footer>`. We would need to add page titles and `href`s. We could get them out of `/contents/index.json` where we can check the previous and the next page.

**Comment by bwinton** [comment]
(Assigning Erica so that she has something to do tomorrow before I wake up.  :wink:)

**Comment by aminalhazwani** [comment]
jfyi the `<footer>` for the page navigation has been moved to `App.jsx`. I think that we could create a `pageNavigation.jsx` component that then we would import in `App.jsx`.
