### ISSUE TITLE
Update for Copy Rules page

### ISSUE THREAD

**Issue by mheubusch** [bwinton/StyleGuide#14]
Can you add the phrases "checkbox labels" and "radio button labels" and create a bulleted list for the terminal punctuation section on the Copy Rules page as follows:

Terminal Punctuation
Do not use punctuation at the end of a 
<ul><li>navigation element 
<li>headline 
<li>button label 
<li>checkbox label
<li>radio button label
<li> text link</ul>
unless you are using an exclamation point or question mark or the link is embedded in running text.

**Comment by aminalhazwani** [comment]
Hi @mheubusch, thanks for your feedback! The [staging website](https://bwinton.github.io/StyleGuide/#/copyrules) should be already up to date. If you have any other update to the remaining sections please feel free to open new issues!
