### ISSUE TITLE
Automated page table of contents generation

### ISSUE THREAD

**Issue by aminalhazwani** [bwinton/StyleGuide#23]
Currently every page features a `<header>` that includes a table of contents for the page itself. This code is manually created and every link points to the `h2`s present in the page. Would it be possible to automatically generate this TOC based on the `h2`s in the content?

**Comment by aminalhazwani** [comment]
This issue depends on #22

**Comment by bwinton** [comment]
Dang, I was thinking of looking into this one…  :wink:

**Comment by ericawright** [comment]
too fast!
