### ISSUE TITLE
Include Tachyons CSS as npm module

### ISSUE THREAD

**Issue by aminalhazwani** [bwinton/StyleGuide#24]
With the exception of `page.scss` all styles are currently set with Tachyons CSS. Would be nice to include it via npm instead of CDN.

**Comment by bwinton** [comment]
So, the only thing installing it locally would give us is the ability to develop when we're offline, but since that isn't something we care about at this time, and since it would conceivably be slower to load this large-ish CSS library inline, we've decided to leave it referencing the CDN for now.
