### ISSUE TITLE
Enable first level pages

### ISSUE THREAD

**Issue by aminalhazwani** [bwinton/StyleGuide#27]
If a first level item in the table of contents has no second level item it should be clickable and it should point to a page. For example on the current website we do not need "Overview" around "Welcome" and "Getting Started" but we would need these last two to be a first level item and they should point to the respective pages.

**Comment by bwinton** [comment]
(I was hoping this would be really easy, but it's not.  Un-assigning myself in case someone else wants to take it. ;) )
