### ISSUE TITLE
Rename .jsx components

### ISSUE THREAD

**Issue by aminalhazwani** [bwinton/StyleGuide#29]
Some components are capitalize, some camel case and other lowercase (`actions.jsx`, `App.jsx`, `TableOfContents.jsx`, ...). I would stick to one naming convention.

**Comment by bwinton** [comment]
There is one naming convention, it's just not explained.  :wink:

Components are capitalized, utility files aren't.  So you can include a `<TableOfContents>` in your code, but you can't include an `<actions>`.  This naming convention allows you to distinguish between them.  (It's also a standard React convention, so breaking from it isn't a great idea.  🙂)

**Comment by aminalhazwani** [comment]
Thanks! We should document it in the [How it works](https://github.com/bwinton/StyleGuide/wiki/How-it-works) wiki page! So that future developers and contributors can follow this convention :)
