### ISSUE TITLE
Incorrect link for the 'Get Started' button

### ISSUE THREAD

**Issue by FatOrangutan** [bwinton/StyleGuide#48]
On the [Welcome page](https://bwinton.github.io/StyleGuide/welcome.html), the big blue 'Get Started' button is linked to https://bwinton.github.io/getting-started.html which doesn't exist. It should probably be https://bwinton.github.io/StyleGuide/getting-started.html.

**Comment by bwinton** [comment]
Being fixed in https://github.com/bwinton/StyleGuide/pull/46

**Comment by FatOrangutan** [comment]
Oh ok, I missed that.

I noticed a couple of things on the Iconography page:

1) Under Placement > Toolbar, the text says "In the toolbar icons are 16px per 16px. They have **16px** margin left and right, center-aligned." But the image immediately below shows a margin of 14px.

2) Panel is supposed to have 32x32 icons as per the table under Placement, but the text under Placement > Panel says "In the toolbar icons are 16px per 16px. They have 16px margin right."

BTW, I realise that this guide is a WIP. Should I refrain from filing issues about minor issues like these that are probably known already?

**Comment by bwinton** [comment]
Probably, although I'll let @aminalhazwani, @brassy-, and @designakt decide how much input they want.  🙂

**Comment by aminalhazwani** [comment]
@FatOrangutan yes, it's a WIP but please feel free to submit issues. This is why we are working in the open!
