### ISSUE TITLE
Make sure people know this StyleGuide only applies starting with Photon

### ISSUE THREAD

**Issue by designakt** [bwinton/StyleGuide#9]
When opening a page of the Staging [StyleGuide](https://bwinton.github.io/StyleGuide/) I might mistake it for the production one if not notified about the fact that this only applies starting with Photon.

I would expect seeing Photon or 57 next to the title in the top left. Maybe like this: 
![styleguide-version-display](https://cloud.githubusercontent.com/assets/8145891/22889998/41078ab0-f20b-11e6-88fc-ff61df7a79b9.PNG)

**Comment by aminalhazwani** [comment]
[4be7c45](https://github.com/bwinton/StyleGuide/commit/4be7c450681bea7bdc26e1380738c2ecce89c4a4) fix this. I close this issue.

**Comment by bwinton** [comment]
@aminalhazwani: Did you want to include the new Photon logo there, too?  🙂

**Comment by aminalhazwani** [comment]
@bwinton actually Stephen said that it wasn't really an official logo 😄
